databases:
  - name: thenetwork
    databaseName: thenetwork
    user: sabrinaaziz13

services:
  - type: web
    name: thenetwork
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn mysite.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
