# Generated by Django 4.2.3 on 2023-07-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('union', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('castingdirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main_app.castingdirector')),
            ],
        ),
    ]
